// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSMA4ZCC67G7ov8cvuOxNd-BjNPgcGsdk',
    appId: '1:528926877023:web:8d5170a632719bf01ec2ea',
    messagingSenderId: '528926877023',
    projectId: 'coffee-mate-6dd64',
    authDomain: 'coffee-mate-6dd64.firebaseapp.com',
    storageBucket: 'coffee-mate-6dd64.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3zUYhy8PqvydyPeXynEXAikSDfUPBHZI',
    appId: '1:528926877023:android:e19819e944afdc591ec2ea',
    messagingSenderId: '528926877023',
    projectId: 'coffee-mate-6dd64',
    storageBucket: 'coffee-mate-6dd64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBFD967z73z17WwsSusqjjUnvIs5z_V0Q',
    appId: '1:528926877023:ios:02d339ae2b926c821ec2ea',
    messagingSenderId: '528926877023',
    projectId: 'coffee-mate-6dd64',
    storageBucket: 'coffee-mate-6dd64.appspot.com',
    iosClientId: '528926877023-3nj18ff0h47crkno963868r3d034jqk5.apps.googleusercontent.com',
    iosBundleId: 'com.helwa.coffeeUI',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBFD967z73z17WwsSusqjjUnvIs5z_V0Q',
    appId: '1:528926877023:ios:66306831e657e4931ec2ea',
    messagingSenderId: '528926877023',
    projectId: 'coffee-mate-6dd64',
    storageBucket: 'coffee-mate-6dd64.appspot.com',
    iosClientId: '528926877023-lvsscqudepicpea4sf312ps4vj24sdt5.apps.googleusercontent.com',
    iosBundleId: 'com.helwa.coffeeUi',
  );
}
